Name: Tutorial1
On: Push

jobs:
    job1: 
        name: job1
        runs-on: ubuntu-latest
        steps:
        -name: step1
        run: echo "Hello from job1"
    job2:
        name: job2
        runs-on: windows-latest
        steps:
        - name: step2
        run: echo "hello from job2"

    job3:
        runs-on:ubuntu-latest
        steps:
        - name: step3
        run: echo "hello from job 3"
